print("=== EXTRACTION COMPARISON ===\n")

print("ACTUAL EXCEL VALUES (from direct verification):")
print("-" * 60)
print("2020:")
print("  Revenue: R$ 1,131,510.61 (FATURAMENTO row)")
print("  Variable Costs: R$ 134,063.82 (CUSTOS VARIÁVEIS row)")
print("  Net Profit: R$ 386,444.33 (RESULTADO C/ RETIRADA PADRÃO row)")
print("\n2021:")
print("  Revenue: R$ 2,036,810.95 (FATURAMENTO row)")
print("  Variable Costs: R$ 261,932.20 (CUSTOS VARIÁVEIS row)")
print("  Net Profit: R$ 11,833.43 (Resultado - Investimentos + Retirada row)")
print("\n2022:")
print("  Revenue: R$ 2,895,603.23 (FATURAMENTO row)")
print("  Variable Costs: R$ 486,710.12 (CUSTOS VARIÁVEIS row)")
print("  Net Profit: R$ 213,986.61 (Resultado - Investimentos - Retirada row)")

print("\n\nEXTRACTOR IS GETTING (from check_extracted_values.py):")
print("-" * 60)
print("2020:")
print("  Revenue: R$ 14,476.14 ❌ (WRONG - missing digits?)")
print("  Variable Costs: R$ 58,741.68 ❌ (WRONG)")
print("  Net Profit: R$ -44,265.54 ❌ (WRONG)")
print("\n2021:")
print("  Revenue: R$ 2,036,810.95 ✓ (CORRECT)")
print("  Variable Costs: R$ 0.44 ❌ (WRONG - getting margin % instead?)")
print("  Net Profit: R$ 2,036,810.51 ❌ (WRONG)")
print("\n2022:")
print("  Revenue: R$ 2,895,603.23 ✓ (CORRECT)")
print("  Variable Costs: R$ 165,934.65 ❌ (WRONG)")
print("  Net Profit: R$ 2,729,668.58 ❌ (WRONG)")

print("\n\nCONCLUSION:")
print("-" * 60)
print("The data extractor is NOT accurately extracting values from the Excel!")
print("It's finding wrong cells or misinterpreting the data structure.")
print("\nThe 1000% anomalies are CORRECT warnings that the extracted data is wrong.")
print("The anomaly detection is working perfectly - it's alerting you to bad data!")
print("\nThe issue is in the direct_extractor.py logic, not the anomaly detection.")