version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      # Simulate production environment
      - RAILWAY_ENVIRONMENT=production
    volumes: []
      # PRODUCTION MODE (default): No volumes = ephemeral storage
      
      # DEVELOPMENT MODE: Uncomment these lines for live editing:
      # - .:/app                    # Mount code for hot reload
      # - /app/__pycache__          # Exclude Python cache
      # - ./data:/app/data          # Persist data locally
      
      # Note: Also change RAILWAY_ENVIRONMENT to 'development' above
    restart: unless-stopped
    
  # Optional: Add a volume for testing persistence
  # data:
  #   driver: local